# Generated by Django 4.2.2 on 2023-06-05 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.habit'),
        ),
    ]
