# Generated by Django 4.2.2 on 2023-06-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_habits_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='done_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
