# Generated by Django 4.2.2 on 2023-06-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_habit_done_today_habit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='done_today',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('goal_status', models.IntegerField(null=True)),
                ('habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.habit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('habit', 'date_completed'), name='habit_date'),
        ),
    ]
