# Generated by Django 4.2.2 on 2023-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_habit_target_alter_habit_done_today_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='good_or_bad',
            field=models.CharField(choices=[('Good', 'Starting A Good Habit'), ('Bad', 'Ending A Bad Habit')], default='Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='type',
            field=models.CharField(choices=[('HR', 'Hours a day'), ('Day', 'Times a day')], default='Day', max_length=20),
        ),
    ]
