# Generated by Django 4.2.2 on 2023-06-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_habit_good_or_bad_alter_habit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='observers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
