# Generated by Django 4.2.2 on 2023-06-12 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment_user_tracker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='observers',
        ),
        migrations.AddField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(related_name='habits_observing', to=settings.AUTH_USER_MODEL),
        ),
    ]
